name: Build and push docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: everest/everest-ci-env

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Dockerfile
      uses: actions/checkout@v2
      with:
        repository: everest/everest-utils
        path: everest-utils
        ref: ${{github.ref}}
        token: ${{secrets.SA_GITHUB_PAT}}
        fetch-depth: 0
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.SA_GITHUB_USERNAME }}
        password: ${{ secrets.SA_GITHUB_PAT }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: everest-utils/docker/everest-ci-env
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}    
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        cache-from: type=gha
        cache-to: type=gha,mode=max
